import { Header } from "@/components";
import RightSidebar from "@/components/RightSidebar";
import Sidebar from "@/components/Sidebar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "dark bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Header />
        <Sidebar />
        <RightSidebar />
        <div className="ml-[16rem] mt-20 p-6">{children}</div>
      </body>
    </html>
  );
}
